### ISSUE TITLE
你好想问个bert的问题，一直在关注你的BERT-Pytorch-Example

### ISSUE THREAD

**Issue by smallliang** [Victor0118/BERT-Fine_tune#1]
为什么分类问题时也需要输入mask_tensor和segment_tentor呢

**Comment by Victor0118** [comment]
@smallliang 不好意思 刚看到
具体看你是单句子分类还是双句子分类, 不过这两个都是需要segment_tentor的. segment_tentor是用来标注token是在第一个还是第二个句子, 如果是单句子就是全0向量.
mask_tensor是bert模型实现的要求输入, 用来区别pad和正常token.
